#!/usr/bin/env python
# -*- coding:utf-8 -*-

from __future__ import print_function, division, unicode_literals



if __name__ == '__main__':
    pass


# vim: set fdm=indent ts=4 sw=4 sts=4 expandtab
# cursor: 5 del
